### ISSUE TITLE
Hello, @ addWebSolution.

### ISSUE THREAD

**Issue by dhiren-basra** [hello-addweb/bottom_navbar_with_indicator#1]
As per your mentioned words : 
_"Will provide fully support with **### assets image (svg, png)** and material icons with **new update**."_

When will this functionality go live? I'm going to wait for it.
Additionally, I'm waiting on a custom widget or image asset to be utilized with the icon property. For example, the default BottomNavigationBarItem() widget contains an icon with a widget return type, allowing us to set any widget. It appears that this package should provide the same features.
I reasoned that by adding this right away, you can attract additional users, who will grow dependent on your above package.

**Comment by sultan-addweb** [comment]
Thank you so much for reminding me to provide full support with assets images (SVG, PNG) and material icons. we will give an update on it very soon.

**Comment by sultan-addweb** [comment]
Hello, @dhiren-basra 
As per your requirement, we have added full support with assets images, and material icons into the bottom bar items.
Now the default BottomNavigationBarItem() widget contains an icon & assets images using its isAssets flag.

**Comment by dhiren-basra** [comment]
Thanks.
